/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;


import TodoApp.util.ConnectionFactory;
import controller.ProjectController;
import controller.TaskController;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Task;

public class App {
   
    public static void main(String[] args) throws SQLException {
        
        ProjectController projectController = new ProjectController();
        
        Project project = new Project();
        
//        project.setName("Poject1");
//        project.setDescription("descricao1");
//        projectController.save(project);
      
//        project.setId(1);
//        project.setName("Novo nome do projeto");
//        projectController.update(project);
        
//        List<Project> projects = projectController.getAll();
//        System.out.println("Total de projetos = " + projects.size());
//        
        
//        projectController.removeById(1);
        
        TaskController taskController = new TaskController();
        
        Task task = new Task();
        
        
        
//        task.setIdProject(2);
//        task.setName("Task1");
//        task.setDescription("DescriptionTask1");
//        task.setNotes("This is task 1");
//        task.setIsCompleted(true);
//        task.setDeadline(new Date());
//        
//        taskController.save(task);

//        task.setIdProject(2);
//        task.setId(3);
//        task.setName("Alteracaoo de status");
//        task.setIsCompleted(false);
//        task.setDeadline(new Date());
//        taskController.update(task);
//
//        List<Task> tasks = taskController.getAll(2);
//        System.out.println("Total de tarefas = " + tasks.size());
        
//        taskController.removeById(3);
        
        
        
        
        
        
        
        
        
       
    }
}
