/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.TaskController;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Project;
import model.Task;

/**
 *
 * @author Keyla
 */
public class TaskEditDialogScreen extends javax.swing.JDialog {
    
     TaskController controller;
     Project project;
     Task task;

    /**
     * Creates new form TaskEditDialogScreen
     */
    public TaskEditDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
       
        initComponents();
        hideErrorFields();
        controller = new TaskController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelToolBarEditTask = new javax.swing.JPanel();
        jLabelToolbarEditTaskTitle = new javax.swing.JLabel();
        jLabelToolbarEditTaskSave = new javax.swing.JLabel();
        jPanelEditTask = new javax.swing.JPanel();
        jLabelEditTaskName = new javax.swing.JLabel();
        jTextFieldEditTaskName = new javax.swing.JTextField();
        jLabelEditTaskNameError = new javax.swing.JLabel();
        jLabelEditTaskDescription = new javax.swing.JLabel();
        jScrollPaneEditTaskDescription = new javax.swing.JScrollPane();
        jTextAreaEditTaskDescription = new javax.swing.JTextArea();
        jLabelEditTaskDeadline = new javax.swing.JLabel();
        jLabelEditTaskDeadlineError = new javax.swing.JLabel();
        jLabelEditTaskNotes = new javax.swing.JLabel();
        jScrollPaneEditTaskNotes = new javax.swing.JScrollPane();
        jTextAreaEditTaskNotes = new javax.swing.JTextArea();
        jFormattedTextFieldEditTaskDeadline = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelToolBarEditTask.setBackground(new java.awt.Color(0, 153, 51));

        jLabelToolbarEditTaskTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelToolbarEditTaskTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelToolbarEditTaskTitle.setText("Editar Tarefas");

        jLabelToolbarEditTaskSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check_white.png"))); // NOI18N
        jLabelToolbarEditTaskSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelToolbarEditTaskSaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelToolBarEditTaskLayout = new javax.swing.GroupLayout(jPanelToolBarEditTask);
        jPanelToolBarEditTask.setLayout(jPanelToolBarEditTaskLayout);
        jPanelToolBarEditTaskLayout.setHorizontalGroup(
            jPanelToolBarEditTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarEditTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelToolbarEditTaskTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelToolbarEditTaskSave)
                .addContainerGap())
        );
        jPanelToolBarEditTaskLayout.setVerticalGroup(
            jPanelToolBarEditTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelToolBarEditTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelToolBarEditTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelToolbarEditTaskTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelToolbarEditTaskSave, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelEditTask.setBackground(new java.awt.Color(255, 255, 255));

        jLabelEditTaskName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEditTaskName.setText("Nome");

        jTextFieldEditTaskName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelEditTaskNameError.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabelEditTaskNameError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelEditTaskNameError.setText("Campo de 'Nome' obrigatório");

        jLabelEditTaskDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEditTaskDescription.setText("Descrição");

        jTextAreaEditTaskDescription.setColumns(20);
        jTextAreaEditTaskDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaEditTaskDescription.setRows(5);
        jScrollPaneEditTaskDescription.setViewportView(jTextAreaEditTaskDescription);

        jLabelEditTaskDeadline.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEditTaskDeadline.setText("Prazo");

        jLabelEditTaskDeadlineError.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabelEditTaskDeadlineError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelEditTaskDeadlineError.setText("Campo de 'Prazo' obrigatório");

        jLabelEditTaskNotes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEditTaskNotes.setText("Notas");

        jTextAreaEditTaskNotes.setColumns(20);
        jTextAreaEditTaskNotes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaEditTaskNotes.setRows(5);
        jScrollPaneEditTaskNotes.setViewportView(jTextAreaEditTaskNotes);

        jFormattedTextFieldEditTaskDeadline.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextFieldEditTaskDeadline.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jFormattedTextFieldEditTaskDeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldEditTaskDeadlineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEditTaskLayout = new javax.swing.GroupLayout(jPanelEditTask);
        jPanelEditTask.setLayout(jPanelEditTaskLayout);
        jPanelEditTaskLayout.setHorizontalGroup(
            jPanelEditTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneEditTaskNotes, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jLabelEditTaskName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldEditTaskName)
                    .addComponent(jLabelEditTaskNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEditTaskDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneEditTaskDescription)
                    .addComponent(jLabelEditTaskDeadline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEditTaskDeadlineError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEditTaskNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldEditTaskDeadline))
                .addContainerGap())
        );
        jPanelEditTaskLayout.setVerticalGroup(
            jPanelEditTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEditTaskName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEditTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEditTaskNameError)
                .addGap(18, 18, 18)
                .addComponent(jLabelEditTaskDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneEditTaskDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelEditTaskDeadline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldEditTaskDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelEditTaskDeadlineError)
                .addGap(18, 18, 18)
                .addComponent(jLabelEditTaskNotes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneEditTaskNotes, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelToolBarEditTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEditTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelToolBarEditTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEditTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldEditTaskDeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldEditTaskDeadlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldEditTaskDeadlineActionPerformed

    private void jLabelToolbarEditTaskSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelToolbarEditTaskSaveMouseClicked
        // TODO add your handling code here:
        try {
            if(isFieldsValid()) {
                task.setIdProject(project.getId());
                task.setName(jTextFieldEditTaskName.getText());
                task.setDescription(jTextAreaEditTaskDescription.getText());
                task.setNotes(jTextAreaEditTaskNotes.getText());
                task.setIsCompleted(false);

                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                Date deadline = null;
                deadline = dateFormat.parse(jFormattedTextFieldEditTaskDeadline.getText());
                task.setDeadline(deadline);

                controller.update(task);

                JOptionPane.showMessageDialog(rootPane, "Tarefa atualizada com sucesso!");
                this.dispose();
            } else {
                hideErrorFields();
                
                if(jTextFieldEditTaskName.getText().isEmpty()) {
                    jLabelEditTaskNameError.setVisible(true);
                }
                
                if(jFormattedTextFieldEditTaskDeadline.getText().isEmpty()) {
                    jLabelEditTaskDeadlineError.setVisible(true);
                }
             
            
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        
        
       
    }//GEN-LAST:event_jLabelToolbarEditTaskSaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskEditDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskEditDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskEditDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskEditDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskEditDialogScreen dialog = new TaskEditDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextFieldEditTaskDeadline;
    private javax.swing.JLabel jLabelEditTaskDeadline;
    private javax.swing.JLabel jLabelEditTaskDeadlineError;
    private javax.swing.JLabel jLabelEditTaskDescription;
    private javax.swing.JLabel jLabelEditTaskName;
    private javax.swing.JLabel jLabelEditTaskNameError;
    private javax.swing.JLabel jLabelEditTaskNotes;
    private javax.swing.JLabel jLabelToolbarEditTaskSave;
    private javax.swing.JLabel jLabelToolbarEditTaskTitle;
    private javax.swing.JPanel jPanelEditTask;
    private javax.swing.JPanel jPanelToolBarEditTask;
    private javax.swing.JScrollPane jScrollPaneEditTaskDescription;
    private javax.swing.JScrollPane jScrollPaneEditTaskNotes;
    private javax.swing.JTextArea jTextAreaEditTaskDescription;
    private javax.swing.JTextArea jTextAreaEditTaskNotes;
    private javax.swing.JTextField jTextFieldEditTaskName;
    // End of variables declaration//GEN-END:variables

    public void setProject(Project project) {
           this.project = project;
       }
    
    public void setTask(Task task) {
        this.task = task;
    }

    public void hideErrorFields() {
        jLabelEditTaskDeadlineError.setVisible(false);
        jLabelEditTaskNameError.setVisible(false);
    }

    public boolean isFieldsValid() {
//        if((!jTextFieldName.getText().isEmpty()) && (!jFormattedTextFieldDeadline.getText().isEmpty())) {
//            return true;
//        } else {
//            return false;
//        }
        return (!jTextFieldEditTaskName.getText().isEmpty()) &&
                (!jFormattedTextFieldEditTaskDeadline.getText().isEmpty());
    }
    



}
